// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/brand/agents/charles.png"
    | "/brand/agents/kai.png"
    | "/brand/favicon/apple-touch-icon.png"
    | "/brand/favicon/favicon-96x96.png"
    | "/brand/favicon/favicon.ico"
    | "/brand/favicon/favicon.svg"
    | "/brand/favicon/site.webmanifest"
    | "/brand/favicon/web-app-manifest-192x192.png"
    | "/brand/favicon/web-app-manifest-512x512.png"
    | "/brand/fonts/Shrikhand/OFL.txt"
    | "/brand/fonts/Shrikhand/Shrikhand-Regular.ttf"
    | "/brand/logo_clean.png"
    | "/content-scripts/content.js"
    | "/inject-provider.js"
    | "/sidepanel.html"
    | "/wallet-window.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
