import { defineConfig } from 'wxt';

// See https://wxt.dev/api/config.html
export default defineConfig({
  srcDir: 'src',
  modules: ['@wxt-dev/module-svelte'],
  runner: {
    disabled: true, // Don't auto-open browser in dev mode
  },
  manifest: {
    name: 'Hominio',
    description: 'Hominio Wallet - Own your data, control your privacy',
    // Use brand icons synced from @hominio/brand
    icons: {
      16: 'brand/favicon/favicon-96x96.png',
      32: 'brand/favicon/favicon-96x96.png',
      48: 'brand/favicon/favicon-96x96.png',
      96: 'brand/favicon/favicon-96x96.png',
      128: 'brand/favicon/web-app-manifest-192x192.png',
    },
    // No default popup - sidepanel entrypoint handles this
    action: {},
    // Permissions
    permissions: ['sidePanel'], // Required for Chrome sidePanel API
    // Content scripts are auto-generated by WXT from entrypoints/content.ts
    // Web accessible resources - make inject-provider.js accessible to web pages
    web_accessible_resources: [
      {
        resources: ['inject-provider.js'],
        matches: ['<all_urls>'],
      },
    ],
  },
});
